### ISSUE TITLE
On Ubuntu LTS. When choosing anime, it shows the loading info text and then show a blank page

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [keerthivasansa/animos#29]
![Screenshot_20230218_103640](https://user-images.githubusercontent.com/68761233/219816797-efecbd07-c8e4-4217-b196-2e015a68b8eb.png)

**Comment by Nectres** [comment]
The app is currently not functional a web version of the app is being built right now with a new design and better sources.

https://www.animos.cf
It will be working in a few days.
