### ISSUE TITLE
Keeps loading when open an anime

### ISSUE THREAD

**Issue by gokul-a-krishnan** [keerthivasansa/animos#30]
![image](https://user-images.githubusercontent.com/36814791/221215268-d16c59f3-a0cf-438b-81f7-b0092e98bdbc.png)

**Comment by thaYt** [comment]
duplicate #29 

the desktop application is not being worked on in favor of a website - https://animos.cf
if you want more info go to the discord @ https://discord.gg/TdfwMSXjeP
